services:
  - type: web
    name: firebase-bi-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python firebase_bi_extension_complete.py
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
