services:
  - type: web
    name: firebase-bi-api
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: FIREBASE_CREDENTIAL_JSON
        sync: false
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
